### ISSUE TITLE
Support newer versions of node

### ISSUE THREAD

**Issue by third774** [nickbalestra/storage-kv#10]
Ran into an issue trying to use https://github.com/jrf0110/8track at home where I'm running Node `v11.12.0` and saw that this package specifies [node v10](https://github.com/nickbalestra/storage-kv/blob/master/package.json#L12) in `package.json`

```
  "engines": {
    "node": "10.x"
  },
```

Could this be updated to be `>=10.x`?

**Comment by nickbalestra** [comment]
Fixed in `v0.0.8`
