### ISSUE TITLE
Remove engine requirements

### ISSUE THREAD

**Issue by robertcepa** [nickbalestra/storage-kv#11]
Related to this https://github.com/nickbalestra/storage-kv/issues/10

But in my case, I need it to support node v8. I cannot upgrade node because of our CI settings.
`error storage-kv@0.0.7: The engine "node" is incompatible with this module. Expected version "10.x". Got "8.11.4"`

Is there any specific reason why is 10.x expected, and if not, can we remove this requirement?

**Comment by manatarms** [comment]
Agreed that the engine might not be required, but to unblock yourself can also lock down Node on CI to `8.11.*`

**Comment by jrf0110** [comment]
That would still bork

**Comment by nickbalestra** [comment]
Fixed in `v0.0.8`
